#griffin_GC_correction.snakefile
#Anna-Lisa Doebley
#Template made 2021-04-06
#Ha Lab
#Fred Hutchinson Cancer Research Center

griffin_scripts_dir: /home/zjp/projects/202402_cfDNAIntegratedTool/cfDNAanalyzer/Griffin/scripts

#################
#mappability bias params##
#################
# #SELECT CORRECT REFERENCE GENOME
# #reference genome for alignment, with index files in same folder as .fa file
reference_genome: /home/zjp/projects/202402_cfDNAIntegratedTool/input/hg19.fa

#chrom sizes for the selected reference genome
chrom_sizes: /home/zjp/projects/202402_cfDNAIntegratedTool/cfDNAanalyzer/Griffin/Ref_hg19/standard.chrom.sizes 

#file containing mappability value for each bp in the genome 
mappability_bw: /home/zjp/projects/202402_cfDNAIntegratedTool/cfDNAanalyzer/Griffin/Ref_hg19/k100.Umap.MultiTrackMappability.bw
mappability_correction: False #whether to run a mappability correction step, we found that this does not improve signals and we do not recommend it 

#bed file containing regions to exclude
encode_exclude: /home/zjp/projects/202402_cfDNAIntegratedTool/cfDNAanalyzer/Griffin/Ref_hg19/encode_unified_exclusion_list.bed
centromeres: /home/zjp/projects/202402_cfDNAIntegratedTool/cfDNAanalyzer/Griffin/Ref_hg19/centromeres.bed
gaps: /home/zjp/projects/202402_cfDNAIntegratedTool/cfDNAanalyzer/Griffin/Ref_hg19/gaps.bed
patches: /home/zjp/projects/202402_cfDNAIntegratedTool/cfDNAanalyzer/Griffin/Ref_hg19/fix_patches.bed
alternative_haplotypes: /home/zjp/projects/202402_cfDNAIntegratedTool/cfDNAanalyzer/Griffin/Ref_hg19/alternative_haplotypes.bed

#where the GC bias output will go
out_dir: /home/zjp/projects/202402_cfDNAIntegratedTool/cfDNAanalyzer/Griffin/snakemakes/griffin_GC_and_mappability_correction/result_case2

#minimum mapping quality to keep a read
map_quality: 20


#################
#GC bias params##
#################
mappable_regions: /home/zjp/projects/202402_cfDNAIntegratedTool/cfDNAanalyzer/Griffin/Ref_hg19/k100_minus_exclusion_lists.mappable_regions.bed

#folder with the gc frequencies for all fragment sizes in the mapable regions (must match the mapable_regions)
#For typical hg38 WGS the correct path is below
genome_GC_frequency: /home/zjp/projects/202402_cfDNAIntegratedTool/cfDNAanalyzer/Griffin/Ref_hg19/genome_GC_frequency

GC_bias_size_range: 15 500
